Person/gryfinn
Ludeon/RimWorld-Polish pull request #150
Opened 2020-11-06 12:31 UTC by Gryfinn

Przetłumaczyłem praktycznie cały folder "HediffDef", poprawiłem literówki, jedyne co zostało to Death Acidifier w Hediffs_BodyParts_Bionic. Niestety u mnie dość słabo z wyobraźnią i nic nie mogłem po polsku wymyślić :P

2020-11-06 13:34 UTC, R4nd0m24 requested changes

2020-11-06 13:34 UTC, R4nd0m24 commented on Core/DefInjected/HediffDef/Hediffs_Global_Misc.xml
> +  <BloodLoss.description>Zmniejszenie ilości krwi w krwiobiegu. Lekka utrata krwi ma względnie łagodne efekty, ale kiedy duża ilość krwi została utracona, transport tlenu w organizmie zostaje osłabio
```suggestion
  <BloodLoss.description>Zmniejszenie ilości krwi w krwiobiegu. Lekka utrata krwi ma względnie łagodne efekty, natomiast utrata dużej ilości powoduje pogorszenie transportu tlenu w organizmie, co prowadzi do utraty przytomności. Utrata większości krwi prowadzi do śmierci. \n\nPoziom krwi w organizmie po pewnym czasie powinien się ustabilizować</BloodLoss.description>
```

2020-11-06 13:34 UTC, R4nd0m24 commented on Core/DefInjected/HediffDef/Hediffs_Global_Needs.xml
> +  <Malnutrition.description>Nieprawidłowo niska waga ciała, zazwyczaj powodowana przez brak jedzenia przez wydłużony okres czasu. Niedożywienie zawsze jest bardzo nieprzyjemne, ale jego początkowe ef
```suggestion
  <Malnutrition.description>Nieprawidłowo niska waga ciała, zazwyczaj spowodowana przez brak jedzenia przez długi okres czasu. Niedożywienie zawsze jest bardzo nieprzyjemne, ale jego początkowe efekty są lekkie. Bez pożywienia, wygłodzony organizm będzie powoli obumierał, tracąc masę mięśniową i tłuszczową. Długi okres niedożywienia kończy się śmiercią. \n\nPo spożyciu jedzenia, niedożywiony organizm zacznie po pewnym czasie wracać do siebie. Niedożywione stworzenia mają większy apetyt niż normalnie.  </Malnutrition.description>
```

2020-11-06 13:34 UTC, R4nd0m24 commented on Core/DefInjected/HediffDef/Hediffs_Global_Temperature.xml
> +  <Heatstroke.description>Zaburzone działanie organizmu spowodowane długim przebywaniem na słońcu i w gorącu. Udar powoduje nudności i ogólne osłabienie. Powrót do zdrowia jest szybki w chłodnym pomi
```suggestion
  <Heatstroke.description>Zaburzone działanie organizmu spowodowane długim przebywaniem na słońcu i w gorącu. Udar powoduje nudności i ogólne osłabienie. Powrót do zdrowia jest szybki w chłodnym pomieszczeniu, lecz wydłużone działanie promieni słonecznych, powoduje że, udar zaczyna się pogłębiać, powodując utratę przytomności, i w ekstremalnych przypadkach, śmierć.</Heatstroke.description>
```

2020-11-06 13:34 UTC, R4nd0m24 commented on Core/DefInjected/HediffDef/Hediffs_Global_Temperature.xml
> +  <Hypothermia.description>Niebezpiecznie niska temperatura ciała. Jeśli organizm szybko nie zostanie ocieplony, hipotermia zacznie się pogarszać, prowadząc do możliwej śmierci. Powrót do zdrowia jes
```suggestion
  <Hypothermia.description>Niebezpiecznie niska temperatura ciała. Jeśli organizm szybko nie zostanie ogrzany, hipotermia zacznie się pogłębiać, prowadząc do śmierci. Powrót do zdrowia jest szybki po ustabilizowaniu temperatury ciała. Unikaj hipotermii nosząc grube, ciepłe ubrania w zimnych klimatach.</Hypothermia.description>
```

2020-11-06 13:34 UTC, R4nd0m24 commented on Core/DefInjected/HediffDef/Hediffs_Global_Temperature.xml
> +  <HypothermicSlowdown.description>Wyjątkowy dla niektórych organizmów stan używany przez nie by przetrwać ekstremalnie zimnych klimatach. Zamiast próbować się ocieplić, organizm przystosowuje się, b
```suggestion
  <HypothermicSlowdown.description>Wyjątkowy dla niektórych organizmów stan który pozwala przetrwać w ekstremalnie zimnych klimatach. Zamiast prób ogrzania się, organizm ogranicza funkcje życiowe, by chronić przed zamarznięciem najważniejsze narządy. Funkcje życiowe w tym stanie są znacząco spowolnione, ale chłód nie wyrządza permanentnej krzywdy istocie. Niektórzy biolodzy nazywają to zjawisko "prymitywną hibernacją".</HypothermicSlowdown.description>
```

2020-11-06 13:34 UTC, R4nd0m24 commented on Core/DefInjected/HediffDef/Hediffs_Local_Chronic.xml
> +  <Alzheimers.description>Choroba mózgu zazwyczaj związana z starzeniem. Choroba alzheimera skutkuje upośledzeniem umiejętności zapamiętywania i myślenia. Chorzy mogą zapominać bliskie im osoby i węd
```suggestion
  <Alzheimers.description>Choroba mózgu zazwyczaj związana z starzeniem. Choroba alzheimera skutkuje upośledzeniem umiejętności zapamiętywania i myślenia. Chorzy mogą zapominać bliskie im osoby i włóczyć się bez celu.</Alzheimers.description>
```

2020-11-06 20:23 UTC, R4nd0m24 requested changes
Taką nazwę wymyśliłem :) Jak jest ok to można merga zrobić.

2020-11-07 11:20 UTC, Gryfinn commented
> Taką nazwę wymyśliłem :) Jak jest ok to można merga zrobić.

Dobra, wygląda kozacko. Wielkie dzięki za pomoc, @R4nd0m24 👍

2020-11-07 11:23 UTC, R4nd0m24 approved these changes
Wszystko fajnie 👍

2020-11-07 11:23 UTC, merged