Dodano tłumaczenia
Ludeon/RimWorld-Polish pull request #155
Opened 2021-06-07 18:37 UTC by Lemongrabb

Dodałem kilka tłumaczeń. Proszę o akceptację zmian.

Postaram się dodać wkrótce więcej tłumaczeń.

2021-06-08 14:26 UTC, Gryfinn requested changes
Są wymagane pewne poprawki; generalnie w porządku, chociaż z okazjonalnymi literówkami.
Rady na przyszłość:
- Nie trzymaj się kurczowo treści oryginału. Jeśli po angielsku jest źle, to nie trzeba kopiować błędów, tylko napisać po swojemu. (Ale tak żeby zachować znaczenie oryginału w jak najlepszy sposób.)
- Wykorzystuj dzisiejszą technologię. Otwórz swój ulubiony edytor tekstu (Osobiście, do tłumaczenia, Visual Studio Code.) Włącz sprawdzanie tekstu, pobierz pluginy na łatwiejsze korzystanie; wszystko co potrzebne by móc łatwo i sprawnie działać.

I tak wielkie dzięki za pomoc i miejmy nadzieję że następnym razem nie trzeba będzie wcale sprawdzać. Ledwo zipie ta nasza grupa tłumaczeniowa i każdy członek jest na wagę złota. 😁👍

2021-06-08 14:26 UTC, Gryfinn commented on Core/Backstories/Backstories.xml
> +    <desc>W odzinie [PAWN_nameDef] było więcej dzieci, niż pełnoprawnych tytułów do odziedziczenia. Będąc jedn{PAWN_gender ? ym : ą} z najmłodszych spośród rodzeństwa, otrzymał{PAWN_gender ? : a} hon
```suggestion
    <desc>W rodzinie należącej do [PAWN_nameDef] było więcej dzieci, niż pełnoprawnych tytułów do odziedziczenia. Będąc jedn{PAWN_gender ? ym : ą} z najmłodszych spośród rodzeństwa, otrzymał{PAWN_gender ? : a} honorowy tytuł {PAWN_gender ? mistrza : mistrzyni} bestii. [PAWN_nameDef] zarządzał{PAWN_gender ? : a} pokaźną menażerią należącą do {PAWN_gender ? jego : jej} rodziny. Chociaż nigdy własnoręcznie nie zajmował{PAWN_gender ? : a} się zwierzętami, to odnalazł{PAWN_gender ? : a} z nimi osobliwą więź. Niektórzy to doceniali, dorywczo {PAWN_gender ? go : ją} zatrudniając .</desc>
```

2021-06-08 14:26 UTC, Gryfinn commented on Core/Backstories/Backstories.xml
> +    <desc>[PAWN_nameDef] był{PAWN_gender ? : a} silnym żołnierzem podczas długiej wojny o sukcesję. W trakcie finałowej bitwy, {PAWN_gender ? jego : jej} oddział został poświęcony, aby osłaniać odwró
```suggestion
    <desc>[PAWN_nameDef] był{PAWN_gender ? : a} silnym żołnierzem podczas długiej wojny o sukcesję. W trakcie finałowej bitwy, {PAWN_gender ? jego : jej} oddział został poświęcony, aby osłaniać odwrót. [PAWN_nameDef] widział{PAWN_gender ? : a} jak {PAWN_gender ? jego : jej} towarzysze umierają. Jako jedyn{PAWN_gender ? y : a} przeżył{PAWN_gender ? : a} starcie.\n\nTo doświadczenie, złamało {PAWN_gender ? go : ją} od środka, wypran{PAWN_gender ? ego : ą} z emocji.\n\nOstatecznie {PAWN_gender ? zaciągnął :  zaciągnęła} się do pracy w szpitalu.</desc>
```

2021-06-08 14:26 UTC, Gryfinn commented on Core/Backstories/Backstories.xml
> +    <desc>Zamiast spędzać czasu z innymi dziećmi, [PAWN_nameDef] wolał{PAWN_gender ? : a} zatracać się w literaturze. Nauczył{PAWN_gender ? : a} się czytać od najmłodszych lat, przy pomocy książek za
```suggestion
    <desc>Zamiast spędzać czas z innymi dziećmi, [PAWN_nameDef] wolał{PAWN_gender ? : a} zatracać się w literaturze. Nauczył{PAWN_gender ? : a} się czytać od najmłodszych lat, przy pomocy książek zakupionych od wędrownych kupców.</desc>
```

2021-06-08 17:29 UTC, Lemongrabb commented
Dzięki za pomoc @Gryfinn, naniosłem poprawki, które wskazałeś w Review. To jest ogólnie mój pierwszy taki Merge Request na githubie, więc nie jestem pewien czy wszystko dobrze zrobiłem, bo dalej widnieje "Changes requested" mimo, że dorzuciłem wszystkie poprawki od Ciebie. Tak czy inaczej, zerknij proszę czy wszystko jest w porządku.

Co do VS Code to używam go regularnie, ale jak dotąd nie pomyślałem, że jest plugin do sprawdzania pisowni. Na pewno go zainstaluje i mam nadzieję, że uniknę tym większości ewentualnych literówek.

W każdym razie, dzięki za pomoc i współpracę i mam nadzieję, jakoś razem wspólnymi siłami spolszczymy całość 😄

2021-06-08 17:32 UTC, Lemongrabb commented on Core/Backstories/Backstories.xml
> +    <title>patron</title>
Poprawiono 👍

2021-06-09 15:01 UTC, Gryfinn approved these changes

2021-06-09 15:17 UTC, Gryfinn commented
No i cudownie! Zaakceptowałem zmiany i merdżuje to z masterem. 
Mam nadzieję że jeszcze wiele razy będę miał okazję współpracować z tobą, tak aby wspólnymi siłami to wszystko w końcu ogarnąć. Cd. Pluginów do VSC (Lub Extensions, jak kto woli):
- Code Spell Checker - Plugin na sprawdzanie tekstu. Szczególnie użyteczny podczas tłumaczenia. Wymaga zainstalowania dodatkowego modułu dla innych języków niż Angielski. Czyli CSC + CSC Polish.
- TODO Highlight - Wyróżnia wszystkie TODO, FIXME, itd. Ułatwiając szukanie niedokończonych tłumaczeń.
- GitHub Pull Requests and Issues - Łączy VSC z GitHubem ułatwiając pracę i pozwalając na, np. commitowanie prosto z Visual Studio Code
- GitLens — Git Supercharged - Cóż, ciężko to ująć w słowa, najlepiej zobaczyć samemu😅. Pozwala na sprawdzenie kiedy i przez kogo dany plik był edytowany, historia commitów i wiele więcej.

Do tego polecam aplikację Git Desktop albo Git Tower (Osobiście korzystam z Git Desktop, ale to już wedle gustu), warte obczajenia i znacząco ułatwiające pracę.

2021-06-09 15:18 UTC, merged